// <auto-generated />
using AspNetCoreMvcSqlSvr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreMvcSqlSvr.Migrations
{
    [DbContext(typeof(MvcShohinContext))]
    [Migration("20230511080601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreMvcSqlSvr.Models.Shohin", b =>
                {
                    b.Property<int>("NumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumId")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumId"));

                    b.Property<decimal>("EditDate")
                        .HasColumnType("decimal(8, 0)")
                        .HasColumnName("EditDate")
                        .HasColumnOrder(3);

                    b.Property<decimal>("EditTime")
                        .HasColumnType("numeric(6, 0)")
                        .HasColumnName("EditTime")
                        .HasColumnOrder(4);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Note")
                        .HasColumnOrder(5);

                    b.Property<short>("ShohinCode")
                        .HasColumnType("smallint")
                        .HasColumnName("ShohinNum")
                        .HasColumnOrder(1);

                    b.Property<string>("ShohinName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("char(50)")
                        .HasColumnName("ShohinName")
                        .HasColumnOrder(2);

                    b.HasKey("NumId");

                    b.ToTable("Shohin");
                });
#pragma warning restore 612, 618
        }
    }
}
